# ------------------------------------------------------------- #
#    █████████            ███                         ████████  #
#   ███░░░░░███          ░░░                         ███░░░░███ #
#  ███     ░░░   ██████  ████  ████████    █████    ░░░    ░███ #
# ░███          ███░░███░░███░ ░███░░███  ███░░        ███████  #
# ░███         ░███ ░███ ░███  ░███ ░███░ ░█████      ███░░░░   #
# ░░███     ███░███ ░███ ░███  ░███ ░███  ░░░░███    ███      █ #
#  ░░█████████ ░░██████  █████ ████ █████ ██████    ░██████████ #
#   ░░░░░░░░░   ░░░░░░  ░░░░░░ ░░░ ░░░░░░ ░░░░░     ░░░░░░░░░░  #
# --- by JustEli --- https://plugin.coins.community/discord --- #

# Defining and configuring the following parts can be done in a different config:
#  - currencies.yml -> Defined currencies
#  - coins.yml      -> Different coin variants
#  - drops.yml      -> Events to drop coins
#  - commands.yml   -> All possible commands

# Language to use for all messages of the plugin. All available languages can be found in
#  the folder 'locale' of the plugin folder. Or create your own in the format 'xx-YY'.
locale: 'en-US'

# Show a message on start-up when an update is available for the plugin.
notify-on-update: true

# Coloring of messages and items. HEX-codes and color names work. Examples: 'dark green',
#  '#197419', 'DARK_AQUA'.
colors:
  primary: f5b62e  # Primary text in messages
  values: f2b794   # Filled in values in messages
  currency: 6dd47e # Displaying currency in messages
  negative: e94b3c # Negative currency in messages
